import {
  GridAreaProps,
  GridGapProps,
  GridColumnProps,
  GridProps as GP,
  GridRowProps,
  SpaceProps,
  SizeProps,
  BackgroundColorProps,
  ColorProps,
  BorderProps,
  BoxShadowProps,
  PositionProps,
  LayoutProps,
  BorderRadiusProps,
  BackgroundProps,
  FlexProps,
  FlexboxProps,
} from 'styled-system';

export interface GridProps
  extends GridAreaProps,
    GridGapProps,
    GridColumnProps,
    GP,
    GridRowProps,
    SpaceProps,
    SizeProps,
    BackgroundColorProps,
    BackgroundProps,
    ColorProps,
    BorderProps,
    BoxShadowProps,
    LayoutProps,
    BorderProps,
    BorderRadiusProps,
    FlexProps,
    FlexboxProps,
    PositionProps {}
